id: medcom.fhir.dk.acknowledgement
canonical: http://medcomfhir.dk/ig/acknowledgement
name: MedComAcknowledgement
title: "DK MedCom acknowledgement"
description: The DK MedCom acknowledgement IG
status: active
version: "2.0.2"
fhirVersion: 4.0.1
copyrightYear: 2021+
releaseLabel: Release
publisher:
  name: MedCom
  url: http://www.medcom.dk
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
dependencies:
  hl7.fhir.dk.core: 2.0.0
  medcom.fhir.dk.core: 2.0.0
  medcom.fhir.dk.messaging: 2.0.0
  medcom.fhir.dk.terminology: 1.4.0



menu:
  Table of Contents: toc.html
  Home: index.html
  Profiles: profiles.html
  Examples: examples.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  Downloads: downloads.html

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
